accounts/urls.py
from django.urls import include, path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.RegisterView.as_view(), name='register'),
]

clubs/urls.py
from django.urls import path

from . import views

app_name = 'clubs'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('create/', views.ClubCreateView.as_view(), name='create-club'),
    path('join/', views.ClubJoinView.as_view(), name='join-club'),
    path('<str:club_name>/', views.ClubDetailView.as_view(), name='club-detail'),
    path('<str:club_name>/meeting/<int:pk>/', views.MeetingDetailView.as_view(), name='meeting-detail'),
    path('<str:club_name>/meeting/<int:pk>/update/', views.MeetingUpdateView.as_view(), name='meeting-update'),
    path('<str:club_name>/meeting/<int:pk>/delete/', views.meeting_delete, name='meeting-delete'),
    path('<str:club_name>/plan', views.PlanMeetingView.as_view(), name='plan-meeting'),
    path('<str:club_name>/proposal/', views.ProposalView.as_view(), name='add-proposal'),
    ]

paper_club/urls.py
from django.contrib import admin
from django.urls import include, path

from .settings import ADMIN_URL

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path(f'{ADMIN_URL}/', admin.site.urls),
    path('clubs/', include('clubs.urls')),
    path('papers/', include('papers.urls')),
]

papers/urls.py
from django.urls import path

from . import views

app_name = 'papers'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<int:pk>/', views.PaperDetailView.as_view(), name='paper-detail'),
    path('add/', views.AddPaperView.as_view(), name='add'),
    path('random/', views.random_paper_view, name='random-paper'),
    
    # path('add/confirm', views.AddConfirmView.as_view(), name='add-confirm'),
    # path('add/confirm', views.AddConfirmView, name='add-confirm'),
    ]

pages/templates/pages/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock title %}
{% block content %}
<p>Created by <a href="https://ajpkim.com">Alex Kim</a>.</p>
<p>Browse source code, report bugs, and whatever else <a href="https://github.com/ajpkim/paper-club">here</a>.</p>
<div id="about-how-to">
  <h2>Paper Club how to:</h2>
  <ol>
    <li>Create or join a club</li>
    <li>Propose papers to the club</li>
    <li>Score other proposals (top-scoring proposals are tracked and visible)</li>
    <li>Schedule a meeting and choose several proposals from among the top-scoring pool of papers to serve as candidates for the upcoming meeting</li>
    <li>Vote on candidates to select the group reading for the meeting</li>
  </ol>
</div>
{% endblock content %}

    

pages/templates/pages/home.html
{% extends 'base.html' %}
{% block title %}Paper Club{% endblock %}

{% block content %}
<h1>Paper Club</h1>
<h3><i>Improve group reading selections</i></h3>
<div class="inner-container">
{% if user.is_authenticated %}

<p><b>{{ user.username }}</b>, go read some papers!</p>
<p>Here's a <a href={% url 'papers:random-paper' %}>random paper</a> to mix things up.</p>



{% else %}
<p>Please <a href="{% url 'login' %}">log in</a> or <a href="{% url 'accounts:register' %}">create an account</a> to participate.</p>
{% endif %}

</div>

{% endblock %}