clubs/urls.py
from django.urls import path

from . import views

app_name = 'clubs'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('create/', views.ClubCreateView.as_view(), name='create-club'),
    path('join/', views.ClubJoinView.as_view(), name='join-club'),
    path('<str:club_name>/', views.ClubDetailView.as_view(), name='club-detail'),
    path('<str:club_name>/meeting/<int:pk>/', views.MeetingDetailView.as_view(), name='meeting-detail'),
    path('<str:club_name>/meeting/<int:pk>/update/', views.MeetingUpdateView.as_view(), name='meeting-update'),
    path('<str:club_name>/meeting/<int:pk>/delete/', views.meeting_delete, name='meeting-delete'),
    path('<str:club_name>/plan', views.PlanMeetingView.as_view(), name='plan-meeting'),
    path('<str:club_name>/proposal/', views.ProposalView.as_view(), name='add-proposal'),
    ]

paper_club/urls.py
from django.contrib import admin
from django.urls import include, path

from .settings import ADMIN_URL

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path(f'{ADMIN_URL}/', admin.site.urls),
    path('clubs/', include('clubs.urls')),
    path('papers/', include('papers.urls')),
]

papers/urls.py
from django.urls import path

from . import views

app_name = 'papers'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<int:pk>/', views.PaperDetailView.as_view(), name='paper-detail'),
    path('add/', views.AddPaperView.as_view(), name='add'),
    path('random/', views.random_paper_view, name='random-paper'),
    
    # path('add/confirm', views.AddConfirmView.as_view(), name='add-confirm'),
    # path('add/confirm', views.AddConfirmView, name='add-confirm'),
    ]

clubs/forms.py
from datetime import datetime, timedelta
import string

from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core import validators
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone

from papers.forms import validate_arxiv_url
from .models import Club, Meeting, Proposal

User = get_user_model()
low, high = 1, 5
SCORE_OPTIONS = [(n, n) for n in range(low, high+1)]


class ClubForm(forms.ModelForm):
    name = forms.CharField(max_length=50, label="Club Name")
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

    class Meta:
        model = Club
        fields = ['name', 'password']


class JoinClubForm(forms.Form):

    club = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        data = self.cleaned_data
        if not Club.objects.filter(name=data['club'], password=data['password']).exists():
            raise ValidationError("No Club matches that combination")


class VoteForm(forms.Form):
    """
    Dynamic form that generates a voting ballot based on the given election.
    """
    def __init__(self, election, *args, **kwargs):
        super(VoteForm, self).__init__(*args, **kwargs)
        self.candidates = election.candidates.all()

        for i, candidate in enumerate(self.candidates, 1):
            self.fields[f'vote_{i}'] = forms.ChoiceField(label=string.ascii_uppercase[i-1], choices=SCORE_OPTIONS)
            self.fields[f'candidate_{i}_id'] = forms.CharField(widget=forms.HiddenInput(), initial=candidate.id)

        self.fields['election_id'] = forms.CharField(widget=forms.HiddenInput(), initial=election.id)
        self.fields['club'] = forms.CharField(widget=forms.HiddenInput(), initial=election.club.name)


class ScoreForm(forms.Form):
    """
    Form for scoring new proposals (not election candidates).
    """
    def __init__(self, proposal, *args, **kwargs):
        self.proposal = proposal
        super(ScoreForm, self).__init__(*args, **kwargs)
        self.fields['score'] = forms.ChoiceField(choices=SCORE_OPTIONS, label="")
        self.fields['proposal_id'] = forms.CharField(widget=forms.HiddenInput(), initial=self.proposal.id)

        

class ProposalForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        self.club = kwargs.pop("club")
        super(ProposalForm, self).__init__(*args, **kwargs)
        self.fields['url'] = forms.URLField(max_length=50, label="arXiv paper URL", validators=[validate_arxiv_url])
        self.fields['score'] = forms.ChoiceField(label="Score", choices=SCORE_OPTIONS)
        self.fields['club'] = forms.ChoiceField(choices=[(club, club) for club in self.request.user.profile.clubs], initial=self.club)
        self.fields['message'] = forms.CharField(widget=forms.Textarea(attrs={'rows': 2}),
                                                 max_length=300,
                                                 required=False)

    def clean(self):
        data = self.cleaned_data
        if 'url' in data and Proposal.objects.filter(Q(paper__url=data['url']) | Q(paper__pdf_url=data['url']),
                                                     club=Club.objects.get(name=self.club)).exists():
            raise ValidationError(f"A proposal for this paper already exists in {self.club}")



def validate_candidate_selection(selected_proposal_ids):
    num = 3
    if len(selected_proposal_ids) != num:
        raise ValidationError(f'Select {num} proposals')

def validate_election_length(length):
    if length <= 0:
        raise ValidationError(f'Pick a valid election length')
    
class MeetingForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        self.proposals = kwargs.pop("proposals")
        self.num_candidates = 3
        super(MeetingForm, self).__init__(*args, **kwargs)
        self.fields['leader'] = forms.CharField(widget=forms.HiddenInput(), initial=self.request.user.username)
        self.fields['date'] = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), label="Meeting date")
        self.fields['time'] = forms.TimeField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}), label="Meeting time")
        self.fields['election_length'] = forms.IntegerField(validators=[validate_election_length], label='Election length (days)')
        self.fields['selected_proposal_ids'] =  forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                                                          choices=self.get_choices(),
                                                                          label=f"Select {self.num_candidates} candidates for group election",
                                                                          validators=[validate_candidate_selection],
                                                                          )

    def get_choices(self):
        return [(x.id, x.paper) for x in self.proposals]

    def clean(self):
        """
        "Handles invalid 5 digit date input by ensuring a valid data object is available for comparison
        and checks if given datetime in future
        """
        data = self.cleaned_data
        if 'date' in data and datetime.now() > datetime.combine(data['date'], data['time']):
            raise ValidationError(f'Pick a valid date')
        


class MeetingUpdateForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.meeting = Meeting.objects.get(pk=kwargs.pop('pk'))
        super(MeetingUpdateForm, self).__init__(*args, **kwargs)
        self.fields['pk'] = forms.CharField(widget=forms.HiddenInput(), initial=self.meeting.id)
        self.fields['date'] = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}),
                                              initial=self.meeting.date_time.date())
        self.fields['time'] = forms.TimeField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}),
                                              initial=self.meeting.date_time.time())
        self.fields['leader'] = forms.CharField(initial=self.meeting.leader)

    def clean(self):
        data = self.cleaned_data

        if ( not User.objects.filter(username=data['leader']).exists() or
             User.objects.get(username=data['leader']) not in self.meeting.club.members.all() ):
             raise ValidationError('Invalid meeting leader')
         
        if 'date' in data and datetime.now() > datetime.combine(data['date'], data['time']):
            raise ValidationError(f'Pick a future date')

clubs/views.py
from datetime import datetime, timedelta
import string

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, FormView, ListView, TemplateView, UpdateView

from papers.utils import process_paper_url
from .models import Candidate, Club, ClubMember, Election, Meeting, Score, Proposal, Vote
from .forms import ClubForm, JoinClubForm, MeetingForm, MeetingUpdateForm, ScoreForm, ProposalForm, VoteForm

User = get_user_model()

class HomeView(ListView):
    template_name = 'clubs/home.html'
    context_object_name = 'user_clubs'

    def get_queryset(self):
        return [x.club for x in ClubMember.objects.filter(member=self.request.user)]


class ClubCreateView(CreateView):
    form_class = ClubForm
    model = Club

    def form_valid(self, form):
        data = form.cleaned_data
        club = Club.objects.create(name=data['name'], password=data['password'])
        ClubMember.objects.create(member=self.request.user, club=club)
        return HttpResponseRedirect(reverse("clubs:club-detail", kwargs={'club_name': club.name}))


class ClubJoinView(FormView):
    form_class = JoinClubForm
    template_name = 'clubs/join-club.html'
    success_url = 'clubs/home'

    def form_valid(self, form):
        data = form.cleaned_data
        club = Club.objects.get(name=data['club'])
        if self.request.user not in club.members.all():
            ClubMember.objects.create(club=club, member=self.request.user)
        return HttpResponseRedirect(reverse("clubs:club-detail", kwargs={'club_name': club.name}))


class ClubDetailView(View):
    template_name = 'clubs/club-detail.html'

    def get_club(self):
        return get_object_or_404(Club, name=self.kwargs['club_name'])

    def get_context_data(self, **kwargs):
        club = self.get_club()
        ctx = club.get_ctx(self.request.user)
        if ctx['election']:
            ctx.update(**ctx['election'].get_ctx(self.request.user))
            if not ctx['voted']:
                ctx['vote_form'] = VoteForm(election=ctx['election'])
                ctx['voteform_fields_candidates_zip'] = list(zip(ctx['election'].candidates.all(),
                                                                 ctx['vote_form'].visible_fields()))
        if ctx['unscored_proposals']:
            ctx['unscored'] = list(map(lambda proposal: (proposal, ScoreForm(proposal)), ctx['unscored_proposals']))

        return ctx

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request, *args, **kwargs):
        data = request.POST
        # Process a VoteForm
        if 'election_id' in data:
            Vote.objects.process_vote_form(request)
        # Process a ScoreForm
        elif 'score' in data:
            Score.objects.create(user = request.user,
                                 proposal = Proposal.objects.get(pk=int(data['proposal_id'])),
                                 score = int(data['score']),
                                 club = self.get_club(),
                                 )

        return HttpResponseRedirect(reverse("clubs:club-detail", kwargs={'club_name': self.get_club().name}))

# TODO
class MeetingDetailView(DetailView):
    template_name = "clubs/meeting-detail.html"
    model = Meeting

    def get_context_data(self, *args, **kwargs):
        pass


class PlanMeetingView(FormView):

    form_class = MeetingForm
    template_name = 'clubs/plan-meeting.html'

    def get_club(self):
        return Club.objects.filter(name=self.kwargs['club_name']).first()

    def get_form_kwargs(self):
        kwargs = super(PlanMeetingView, self).get_form_kwargs()
        kwargs.update({'request': self.request,
                       'proposals': self.get_club().top_proposals,
                       })
        return kwargs

    def form_valid(self, form):
        data = form.cleaned_data
        election = Election.objects.create(club=self.get_club(),
                                           end_datetime=timezone.now() + timedelta(days=+data['election_length']))

        for prop_id in data['selected_proposal_ids']:
            Candidate.objects.create(election=election, proposal=Proposal.objects.get(pk=int(prop_id)))

        Meeting.objects.create(club=self.get_club(),
                               leader=User.objects.get(username=data['leader']),
                               election=election,
                               date_time=datetime.combine(data['date'], data['time']),
                               )

        return HttpResponseRedirect(reverse("clubs:club-detail", kwargs={'club_name': self.get_club().name}))


class MeetingUpdateView(FormView):

    form_class = MeetingUpdateForm
    template_name = 'clubs/meeting-update.html'

    def get_form_kwargs(self):
        kwargs = super(MeetingUpdateView, self).get_form_kwargs()
        kwargs.update({'pk': self.kwargs['pk']})  # self.kwargs contains club_name and pk (meeting pk)
        return kwargs

    def form_valid(self, form):
        data = form.cleaned_data
        meeting = Meeting.objects.get(pk=data['pk'])
        meeting.date_time = datetime.combine(data['date'], data['time'])
        meeting.leader = User.objects.get(username=data['leader'])
        meeting.save()

        return HttpResponseRedirect(reverse("clubs:club-detail", kwargs={'club_name': meeting.club.name}))


def meeting_delete(request, *args, **kwargs):
    meeting = get_object_or_404(Meeting, pk=kwargs['pk'])
    club = meeting.club

    if request.method == 'POST':
        meeting.election.delete()
        meeting.delete()
        return HttpResponseRedirect(reverse('clubs:club-detail', kwargs={'club_name': meeting.club.name}))

    return HttpResponseRedirect(club.get_absolute_url())


class ProposalView(FormView):

    form_class = ProposalForm
    template_name = 'clubs/add-proposal.html'

    def get_form_kwargs(self):
        kwargs = super(ProposalView, self).get_form_kwargs()
        kwargs.update({'request': self.request,
                       'club': self.kwargs['club_name'],
                       })
        return kwargs

    def form_valid(self, form):
        """
        Create corresponding Paper, Author, Proposal, and Score database entries.
        """
        data = form.cleaned_data
        url = data['url']
        user = self.request.user
        club = Club.objects.get(name=data['club'])
        msg = data['message']
        paper, authors = process_paper_url(url)

        proposal = Proposal.objects.create(user=user,
                                           paper=paper,
                                           club=club,
                                           msg=msg,
                                           )
        Score.objects.create(user=user,
                             proposal=proposal,
                             score=data['score'],
                             club=club,
                             )

        return HttpResponseRedirect(reverse('clubs:club-detail', kwargs={'club_name': club.name}))

clubs/templates/clubs/add-proposal-btn.html
<button type="submit" id="plan-meeting-btn" onclick="location.href='{% url 'clubs:plan-meeting' club %}'">Plan Meeting</button>

clubs/templates/clubs/add-proposal.html
{% extends 'base.html' %}
{% block title %}Proposal{% endblock %}
{% block content %}
<h2>Propose a Paper</h2>
  <form method="POST" id="add-proposal-form" name="add-proposal-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="Submit">Add</button>
  </form>
  {% endblock %}

clubs/templates/clubs/club-detail.html
{% extends 'base.html' %}
{% block title %}{{ club.name }}{% endblock title %}
{% block content %}

<h1>{{ club.name }}</h1>

<details>
  <summary><b>Members</b></summary>
<ul>
  {% for member in club.members.all %}
  <li>{{ member }}</li>
  {% endfor %}
</ul>
</details>

<button type="submit" id="add-proposal-btn" onclick="location.href='{% url 'clubs:add-proposal' club.name %}'">Add Proposal</button>

{% if meeting %}
{% include 'clubs/meeting.html' %}
{% else %}
<button type="submit" id="plan-meeting-btn" onclick="location.href='{% url 'clubs:plan-meeting' club %}'">Plan Meeting</button>
{% endif %}

{% if unscored_proposals %}
{% include 'clubs/unscored_proposals.html' %}
{% endif %}

{% if club.proposals.all %}
{% include 'clubs/top-proposals.html' %}
{% endif %}

{% endblock content %}

clubs/templates/clubs/club.html
{% extends 'base.html' %}
{% block title %}{{ club.name }}{% endblock title %}
{% block content %}

<h1>{{ club.name }}</h1>


<button type="submit" id="add-proposal-btn" onclick="location.href='{% url 'clubs:add-proposal' club.name %}'">Add Proposal</button>

<!-- <details> -->
<!--   <summary>Add a Paper</summary> -->
<!-- </details> -->

<br>
<br>

<details>
  <summary><b>Members</b></summary>
<ul>
  {% for member in club.users.all %}
  <li>{{ member }}</li>
  {% endfor %}
</ul>
</details>


{% if election %}
{% include 'clubs/vote.html' %}
{% endif %}


{% if unscored_proposals %}
{% include 'clubs/score.html' %}
{% endif %}


{% include 'clubs/proposals.html' %}



{% endblock content %}

clubs/templates/clubs/club_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Create a New Reading Club</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create">
</form>
{% endblock %}

clubs/templates/clubs/home.html
{% extends 'base.html' %}
{% block title %}Clubs{% endblock title %}
{% block content %}


<div id="club-btns-container">
    <button type="submit" id="join-club-btn" onclick="location.href='{% url 'clubs:join-club' %}'">Join Club</button>
  <button type="submit" id="create-club-btn" onclick="location.href='{% url 'clubs:create-club' %}'">Create Club</button>

  </div>

<h2>My Clubs</h2>
<ul>
  {% for club in user_clubs %}
  <li><a href="{% url 'clubs:club-detail' club.name  %}">{{ club }}</a></li>
  {% endfor %}
</ul>

{% endblock content %}

clubs/templates/clubs/join-club.html
{% extends 'base.html' %}
{% block content %}
<h1>Join a Reading Club</h1>
{% if error_msg %}
<p><b>No match for club/password combo</b></p>
{% endif %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Join">
</form>
{% endblock %}

clubs/templates/clubs/meeting-detail.html
{% extends 'base.html' %}
{% block title %}Meeting Info{% endblock title %}
{% block content %}

Come back later :)


{% endblock %}

clubs/templates/clubs/meeting.html
<h2>Next Meeting</h2>
<div id="meeting-container">
  <p><b>When: </b>{{ meeting.date_time }}</p>
  {% if club.election %}
  <p>Hours left in election: {{ election.hours_left }}</p>
  {% include 'clubs/update-meeting-btn.html' %}
  {% if voted %}
  <details>
    <summary><i>awaiting election results on the following proposals</i></summary>
    <ul>
      {% for candidate in election.candidates.all %}
      <li><a href="{% url 'papers:paper-detail' candidate.paper.id %}">{{candidate.paper}}</li>
      {% endfor %}
    </ul>
  </details>
  {% else %}
  {% include 'clubs/vote.html' %}
  {% endif %}
  {% else %}
  <p><b>Paper: </b><a href="{% url 'papers:paper-detail' meeting.paper.id %}">{{ meeting.paper }}</a></p>
  <p><b>Leader: </b>{{ meeting.leader }}</p>
  {% include 'clubs/update-meeting-btn.html' %}
  {% endif %}
</div>

clubs/templates/clubs/plan-meeting.html
{% extends 'base.html' %}

{% block content %}
<h2>Plan Meeting</h2>
  <form method="POST" id="plan-meeting-form" name="plan-meeting-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="Submit">Add</button>
  </form>
{% endblock %}

clubs/templates/clubs/top-proposals.html
<h2>Top Proposals</h2>
<div id="top-proposals-container">

<ol>
{% for proposal in top_proposals %}
<li><a href="{% url 'papers:paper-detail' proposal.paper.id %}">{{ proposal.paper.title }}</a></li>
{% if proposal.msg %}
<ul>
  <li><i>"{{ proposal.msg }}"</i></li>
</ul>
{% endif %}
{% endfor %}

</ol>
</div>

clubs/templates/clubs/unscored_proposals.html
<h2>Unscored Proposals</h2>
<div id="unscored-proposals-container">

<ul>
{% for proposal, form in unscored %}
<li><a href="{% url 'papers:paper-detail' proposal.paper.id %}">{{ proposal.paper }}</a></li>
{% if proposal.msg %}
<ul>
  <li><i>"{{ proposal.msg }}"</i></li>
</ul>
{% endif %}

<form method="POST" class="score-proposal-form", name="score-proposal-form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="Submit">Score</button>
</form>

{% endfor %}
</ul>
</div>

clubs/templates/clubs/update-meeting-btn.html
  <button type="submit" class="update-btn" onclick="location.href='{% url 'clubs:meeting-update' club.name meeting.id %}'">Update Meeting</button>

clubs/templates/clubs/vote.html
<h2>Vote</h2> 
<div id="vote-container">
  <form method="POST" id="vote-form"  name="vote-form">
    {% csrf_token %}
    {{ vote_form.as_p }}
    <button type="submit">Vote</button>
  </form>

  <div id="candidates">
    {% for i, candidate in candidates.items %}
    <p><b>{{ i }}:</b> <a href="{% url 'papers:paper-detail' candidate.paper.id %}">{{ candidate.paper.title }}</a>
      {% endfor %}
  </div>
</div>