accounts/urls.py
from django.urls import include, path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.RegisterView.as_view(), name='register'),
]

clubs/urls.py
from django.urls import path

from . import views

app_name = 'clubs'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('create/', views.ClubCreateView.as_view(), name='create-club'),
    path('join/', views.ClubJoinView.as_view(), name='join-club'),
    path('<str:club_name>/', views.ClubDetailView.as_view(), name='club-detail'),
    path('<str:club_name>/meeting/<int:pk>/', views.MeetingDetailView.as_view(), name='meeting-detail'),
    path('<str:club_name>/meeting/<int:pk>/update/', views.MeetingUpdateView.as_view(), name='meeting-update'),
    path('<str:club_name>/meeting/<int:pk>/delete/', views.meeting_delete, name='meeting-delete'),
    path('<str:club_name>/plan', views.PlanMeetingView.as_view(), name='plan-meeting'),
    path('<str:club_name>/proposal/', views.ProposalView.as_view(), name='add-proposal'),
    ]

pages/urls.py
from django.urls import include, path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
]

paper_club/urls.py
from django.contrib import admin
from django.urls import include, path

from .settings import ADMIN_URL

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path(f'{ADMIN_URL}/', admin.site.urls),
    path('clubs/', include('clubs.urls')),
    path('papers/', include('papers.urls')),
]

papers/urls.py
from django.urls import path

from . import views

app_name = 'papers'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<int:pk>/', views.PaperDetailView.as_view(), name='paper-detail'),
    path('add/', views.AddPaperView.as_view(), name='add'),
    path('random/', views.random_paper_view, name='random-paper'),
    
    # path('add/confirm', views.AddConfirmView.as_view(), name='add-confirm'),
    # path('add/confirm', views.AddConfirmView, name='add-confirm'),
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <title>{% block title %}PC{% endblock %}</title>
  </head>
  <body>
    <div id="container">
      {% include "navbar.html" %}
      <div id="content">
    {% block content %}{% endblock %}
      </div>
    </div>
  </body>
</html>

templates/navbar.html
<div id="navBar">
  <a href="{% url 'pages:home' %}">Home</a> |
  {% if user.is_authenticated %}
  <!-- Papers section in progress... -->
<!-- <a href="{% url 'papers:home' %}">Papers</a> | -->
  <a href="{% url 'clubs:home' %}">Clubs</a> |
  <a href="{% url 'pages:about' %}">About</a> |
  <a href="{% url 'logout' %}">Log out</a>
  {% else %}
  <a href="{% url 'pages:about' %}">About</a> |
  <a href="{% url 'login' %}">Login</a> |
  <a href="{% url 'accounts:register' %}">Join</a>
  {% endif %}
</div>